### ISSUE TITLE
One of the EventListeners had an uncaught exception

### ISSUE THREAD

**Issue by MrS4UL23** [Bennyboy1695/BetterDiscordBridge#10]
I got this error when trying to start the plugin

![log-error](https://user-images.githubusercontent.com/46073220/110670184-1a888280-819b-11eb-999e-705c15706ccb.PNG)

**Comment by MCUmbrella** [comment]
https://github.com/X-Niter/BetterDiscordBridge
use this fork and build this plugin by yourself

**Comment by MrS4UL23** [comment]
@MCUmbrella  Could you help me with that? I do not understand anything. I would greatly appreciate it

**Comment by MCUmbrella** [comment]
https://drive.google.com/file/d/1MYAjSGti_J5gNKzRxaj6EAyab_8VeLQb/view?usp=sharing

**Comment by MrS4UL23** [comment]
@MCUmbrella  Thanks man.
