### ISSUE TITLE
Fix Chat duplication

### ISSUE THREAD

**Issue by X-Niter** [Bennyboy1695/BetterDiscordBridge#8]
[Bug]
I plan to take a look at this.  Putting this here for communication's sake.

Sending a message in-game relays to discord and then back to the game.

![Capture](https://user-images.githubusercontent.com/30506033/93450320-741e8d00-f89b-11ea-987b-943c72892eb4.PNG)

Most likely a simple "Ignore bot" method.

**Comment by Bennyboy1695** [comment]
That if statement existed before the recent update, so must have been removed in your pull 😛

**Comment by X-Niter** [comment]
> That if statement existed before the recent update, so must have been removed in your pull 😛

Yeah most likely, I thought I kept it in there for clear reasons, but have fat fingered something.
